Repository woowa-techcamp-2024/java-chess, pull requests merged in 2024-07, with the labels that each got.

#200 [seminchoi] step-8 GUI나 웹으로 구현
  README.md
  src/main/java/wootecamp/chess/Main.java
  src/main/java/wootecamp/chess/board/Board.java
  src/main/java/wootecamp/chess/board/BoardPosition.java
  src/main/java/wootecamp/chess/board/Direction.java
  src/main/java/wootecamp/chess/board/MoveVector.java
  src/main/java/wootecamp/chess/game/ConsoleGameFactory.java
  src/main/java/wootecamp/chess/game/ConsoleGameInputManager.java
  src/main/java/wootecamp/chess/game/ConsoleGameOutputManager.java
  src/main/java/wootecamp/chess/game/Game.java
  src/main/java/wootecamp/chess/game/GameFactory.java
  src/main/java/wootecamp/chess/game/GameInputManager.java
  src/main/java/wootecamp/chess/game/GameOutputManager.java
  src/main/java/wootecamp/chess/game/State.java
  src/main/java/wootecamp/chess/game/client/ConsoleGameClient.java
  src/main/java/wootecamp/chess/game/client/swing/BoardPanel.java
  src/main/java/wootecamp/chess/game/client/swing/GameFrame.java
  src/main/java/wootecamp/chess/game/client/swing/SquareButton.java
  src/main/java/wootecamp/chess/game/client/swing/SwingGameClient.java
  src/main/java/wootecamp/chess/game/state/EndState.java
  src/main/java/wootecamp/chess/game/state/PlayingState.java
  src/main/java/wootecamp/chess/game/state/ReadyState.java
  src/main/java/wootecamp/chess/game/state/State.java
  src/main/java/wootecamp/chess/pieces/Bishop.java
  src/main/java/wootecamp/chess/pieces/Direction.java
  src/main/java/wootecamp/chess/pieces/EmptyPiece.java
  src/main/java/wootecamp/chess/pieces/King.java
  src/main/java/wootecamp/chess/pieces/Knight.java
  src/main/java/wootecamp/chess/pieces/MovableDirection.java
  src/main/java/wootecamp/chess/pieces/Pawn.java
  src/main/java/wootecamp/chess/pieces/Piece.java
  src/main/java/wootecamp/chess/pieces/PieceComparator.java
  src/main/java/wootecamp/chess/pieces/Queen.java
  src/main/java/wootecamp/chess/pieces/Rook.java
  src/test/java/wootecamp/chess/game/GameTest.java
Labels: Step1-8

#199 [step-7] 예외 처리
  .gradle/8.5/executionHistory/executionHistory.lock
  .gradle/8.5/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/Main.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  chess/.gitignore
  chess/.idea/.gitignore
  chess/.idea/gradle.xml
  chess/.idea/misc.xml
  chess/.idea/vcs.xml
  chess/READMe.md
  chess/build.gradle
  chess/gradle/wrapper/gradle-wrapper.jar
  chess/gradle/wrapper/gradle-wrapper.properties
  chess/gradlew
  chess/gradlew.bat
  chess/settings.gradle
  chess/src/main/java/chess/Board.java
  chess/src/main/java/chess/BoardArea.java
  chess/src/main/java/chess/ChessGame.java
  chess/src/main/java/chess/Main.java
  chess/src/main/java/chess/Position.java
  chess/src/main/java/chess/Rank.java
  chess/src/main/java/exception/InvalidMoveException.java
  chess/src/main/java/exception/OutOfBoardException.java
  chess/src/main/java/pieces/Bishop.java
  chess/src/main/java/pieces/Blank.java
  chess/src/main/java/pieces/King.java
  chess/src/main/java/pieces/Knight.java
  chess/src/main/java/pieces/Pawn.java
  chess/src/main/java/pieces/Piece.java
  chess/src/main/java/pieces/PieceColor.java
  chess/src/main/java/pieces/PieceDescriptor.java
  chess/src/main/java/pieces/PieceFactory.java
  chess/src/main/java/pieces/PieceType.java
  chess/src/main/java/pieces/PieceUnicode.java
  chess/src/main/java/pieces/Queen.java
  chess/src/main/java/pieces/Rook.java
  chess/src/main/java/util/Order.java
  chess/src/test/java/chess/BoardTest.java
  chess/src/test/java/chess/ChessGameTest.java
  chess/src/test/java/pieces/BishopTest.java
  chess/src/test/java/pieces/KingTest.java
  chess/src/test/java/pieces/KnightTest.java
  chess/src/test/java/pieces/PieceDescriptorTest.java
  chess/src/test/java/pieces/PieceFactoryTest.java
  chess/src/test/java/pieces/PieceTest.java
  chess/src/test/java/pieces/QueenTest.java
  chess/src/test/java/pieces/RookTest.java
  src/main/java/chess/Main.java
Labels: Step1-7

#198 [HyeonJun0530] step-6 기물 이동 구현
  src/main/java/chess/Rule.java
Labels: Step1-6

#182 [kkyu0718] step-6,7 기물 이동 구현, 예외처리
  .gitignore
  .idea/.gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  java-chess.iml
  java-chess/src/main/java/org/example/Main.java
  java-chess/src/main/java/org/example/chess/Board.java
  java-chess/src/main/java/org/example/chess/pieces/global/Position.java
  java-chess/src/test/java/org/example/chess/BoardTest.java
  java-chess/src/test/java/org/example/chess/pieces/PieceTest.java
  settings.gradle.kts
  src/main/java/org/example/Main.java
  src/main/java/org/example/chess/Board.java
  src/main/java/org/example/chess/Chess.java
  src/main/java/org/example/chess/ChessView.java
  src/main/java/org/example/chess/MoveActioner.java
  src/main/java/org/example/chess/MoveVerifier.java
  src/main/java/org/example/chess/pieces/Bishop.java
  src/main/java/org/example/chess/pieces/King.java
  src/main/java/org/example/chess/pieces/Knight.java
  src/main/java/org/example/chess/pieces/Movable.java
  src/main/java/org/example/chess/pieces/NoPiece.java
  src/main/java/org/example/chess/pieces/Pawn.java
  src/main/java/org/example/chess/pieces/Piece.java
  src/main/java/org/example/chess/pieces/Queen.java
  src/main/java/org/example/chess/pieces/Rook.java
  src/main/java/org/example/chess/pieces/global/Direction.java
  src/main/java/org/example/chess/pieces/global/Move.java
  src/main/java/org/example/chess/pieces/global/MoveSeq.java
  src/main/java/org/example/chess/pieces/global/Order.java
  src/main/java/org/example/chess/pieces/global/Position.java
  src/main/java/org/example/utils/StringUtils.java
  src/test/java/org/example/chess/BoardTest.java
  src/test/java/org/example/chess/MoveVerifierTest.java
  src/test/java/org/example/chess/pieces/PieceTest.java
Labels: Step1-6, Step1-7

#201 [HiiWee] step-7 예외처리
  src/main/java/com/wootecam/chess/ChessApplication.java
  src/main/java/com/wootecam/chess/ChessView.java
  src/main/java/com/wootecam/chess/ExceptionResolver.java
  src/main/java/com/wootecam/chess/GameCommand.java
  src/main/java/com/wootecam/chess/game/Game.java
  src/main/java/com/wootecam/chess/utils/TriConsumer.java
Labels: Step1-7
