Repository woowa-techcamp-2024/java-chess, pull requests merged in 2024-06, with the labels that each got.

#1 [Lechros] step-1 체스 프로젝트 시작
  java-chess.iml
  src/main/piece/Pawn.java
  src/test/piece/PawnTest.java
Labels: Step1-1

#2 [huiseung] step-1 체스 프로젝트 시작
  chess/.gitignore
  chess/.idea/.gitignore
  chess/.idea/gradle.xml
  chess/.idea/misc.xml
  chess/.idea/vcs.xml
  chess/build.gradle
  chess/gradle/wrapper/gradle-wrapper.jar
  chess/gradle/wrapper/gradle-wrapper.properties
  chess/gradlew
  chess/gradlew.bat
  chess/settings.gradle
  chess/src/main/java/chess/Pawn.java
  chess/src/test/java/chess/PawnTest.java
Labels: Step1-1

#3 [kariskan] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step1-1

#4 [kimhyun5u] step-1 체스 프로젝트 시작
  .gitignore
  pom.xml
  src/main/java/pieces/Pawn.java
  src/test/java/pieces/PawnTest.java
Labels: Step1-1

#5 [김규원] step-1 체스 프로젝트 시작
  .gitignore
  java-chess/build.gradle.kts
  java-chess/gradle/wrapper/gradle-wrapper.properties
  java-chess/gradlew
  java-chess/gradlew.bat
  java-chess/settings.gradle.kts
  java-chess/src/main/java/org/example/Main.java
  java-chess/src/main/java/org/example/character/Pawn.java
  java-chess/src/test/java/PawnTest.java
Labels: Step1-1

#6 [이경민] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/test/java/pieces/PawnTest.java
Labels: Step1-1

#7 [HiiWee] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/wootecam/Pawn.java
  src/test/java/com/wootecam/PawnTest.java
Labels: Step1-1

#8 [hseong3243] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/seong/Main.java
  src/main/java/com/seong/chess/Pawn.java
  src/main/java/com/seong/chess/Piece.java
  src/test/java/com/seong/chess/PawnTest.java
Labels: Step1-1

#9 [minnim1010] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/wootecam/Pawn.java
  src/test/java/com/wootecam/PawnTest.java
Labels: Step1-1

#10 [Chhs2131] step-1 체스 프로젝트 시작
  build.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step1-1

#11 [lass9436] step-1 체스 프로젝트 시작
  .gitignore
  .idea/.gitignore
  chess.iml
  chess/build.gradle
  chess/gradle/wrapper/gradle-wrapper.properties
  chess/gradlew
  chess/gradlew.bat
  chess/settings.gradle
  chess/src/main/java/lass9436/Main.java
  chess/src/test/java/Pawn.java
  chess/src/test/java/PawnTest.java
Labels: Step1-1

#12 [hellomatia] step-1 체스 프로젝트 시작
  src/main/java/com.woowatechcamp/Color.java
  src/main/java/com.woowatechcamp/Pawn.java
  src/test/java/com/woowatechcamp/PawnTest.java
Labels: Step1-1

#13 [Dr-KoKo] step-1 체스 프로젝트 시작
  .gitignore
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/pe/goblin/Main.java
  src/test/java/pe/goblin/pawn/Pawn.java
  src/test/java/pe/goblin/pawn/PawnTest.java
Labels: Step1-1

#14 [bellringstar] step-1 체스 프로젝트 시작
  chess-procjet/.gitignore
  chess-procjet/build.gradle
  chess-procjet/gradle/wrapper/gradle-wrapper.jar
  chess-procjet/gradle/wrapper/gradle-wrapper.properties
  chess-procjet/gradlew
  chess-procjet/gradlew.bat
  chess-procjet/settings.gradle
  chess-procjet/src/main/java/org/example/Main.java
  chess-procjet/src/main/java/org/example/piece/Pawn.java
  chess-procjet/src/test/java/org/example/piece/PawnTest.java
Labels: Step1-1

#15 [LuizyHub] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/chess/Main.java
  src/main/java/chess/piece/Pawn.java
  src/test/java/chess/piece/PawnTest.java
Labels: Step1-1

#17 [Hyeon-Uk] step-1 체스 프로젝트 시작
  .gitignore
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  chess/.idea/workspace.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step1-1

#18 [KoKimSS] step-1 체스 프로젝트 시작
  .DS_Store
  .gitignore
  woowa_camp_chess/.gitignore
  woowa_camp_chess/build.gradle
  woowa_camp_chess/gradle/wrapper/gradle-wrapper.jar
  woowa_camp_chess/gradle/wrapper/gradle-wrapper.properties
  woowa_camp_chess/gradlew
  woowa_camp_chess/gradlew.bat
  woowa_camp_chess/settings.gradle
  woowa_camp_chess/src/main/java/org/example/Main.java
  woowa_camp_chess/src/main/java/org/example/board/Board.java
  woowa_camp_chess/src/main/java/org/example/pieces/Pawn.java
  woowa_camp_chess/src/test/java/org/example/board/BoardTest.java
  woowa_camp_chess/src/test/java/org/example/pieces/PawnTest.java
Labels: Step1-1

#20 [miiiinju1] step-1 체스 프로젝트 시작
  .gitignore
  .idea/.gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/chess/Pawn.java
  src/test/java/chess/PawnTest.java
Labels: Step1-1

#21 [yudonggeun] step-1 체스 프로젝트 시작
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/demo/DemoApplication.java
  src/main/java/com/example/demo/piece/Pawn.java
  src/test/java/com/example/demo/piece/PawnTest.java
Labels: Step1-1

#22 [i960107] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step1-1

#24 [minseok-oh] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/chess/Pawn.java
  src/test/java/chess/PawnTest.java
Labels: Step1-1

#25 [jcw1031] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/woopaca/javachess/Board.java
  src/main/java/com/woopaca/javachess/Pawn.java
  src/test/java/com/woopaca/javachess/BoardTest.java
  src/test/java/com/woopaca/javachess/PawnTest.java
Labels: Step1-1

#26 [june-777] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/woowa/camp/Pawn.java
  src/test/java/woowa/camp/PawnTest.java
Labels: Step1-1

#27 [hseong3243] step-2 체스판 생성
  src/main/java/com/seong/chess/Board.java
  src/main/java/com/seong/chess/pieces/Pawn.java
  src/main/java/com/seong/chess/pieces/Piece.java
  src/test/java/com/seong/chess/BoardTest.java
  src/test/java/com/seong/chess/pieces/PawnTest.java
Labels: Step1-2

#28 [HiiWee] step-2 체스판 생성
  src/main/java/com/wootecam/Pawn.java
  src/main/java/com/wootecam/chess/Board.java
  src/main/java/com/wootecam/chess/pieces/Pawn.java
  src/test/java/com/wootecam/chess/BoardTest.java
  src/test/java/com/wootecam/chess/pieces/PawnTest.java
Labels: Step1-2

#29 [minnim1010] step-2 체스판 생성
  src/main/java/com/wootecam/Pawn.java
  src/main/java/com/wootecam/chess/Board.java
  src/main/java/com/wootecam/chess/Color.java
  src/main/java/com/wootecam/chess/pieces/Pawn.java
  src/test/java/com/wootecam/chess/BoardTest.java
  src/test/java/com/wootecam/chess/pieces/PawnTest.java
Labels: Step1-2

#30 [이경민] step-2 체스판 생성
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/enums/Color.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step1-2

#31 [kimhyun5u] step-2 체스판 생성
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-2

#32 [kariskan] step-2 체스판 생성
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/pieces/Color.java
  src/main/java/pieces/Pawn.java
  src/test/java/PawnTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step1-2

#33 [huiseung] step-2 체스판 생성
  chess/.idea/gradle.xml
  chess/src/main/java/chess/Board.java
  chess/src/main/java/pieces/Pawn.java
  chess/src/main/java/pieces/PawnColor.java
  chess/src/test/java/chess/BoardTest.java
  chess/src/test/java/chess/PawnTest.java
  chess/src/test/java/pieces/PawnTest.java
Labels: Step1-2

#34 [seminchoi] step-1 체스 프로젝트 시작
  src/main/java/wootecamp/chess/Pawn.java
  src/test/java/wootecamp/chess/PawnTest.java
Labels: Step1-1

#35 [LuizyHub] step-2 체스판 생성
  src/main/java/chess/Board.java
  src/main/java/chess/piece/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PawnTest.java
Labels: Step1-2

#36 [bellringstar] step-2 체스판 생성
  chess-procjet/src/main/java/org/example/chess/board/Board.java
  chess-procjet/src/main/java/org/example/chess/pieces/Color.java
  chess-procjet/src/main/java/org/example/chess/pieces/Pawn.java
  chess-procjet/src/main/java/org/example/piece/Pawn.java
  chess-procjet/src/test/java/org/example/chess/board/BoardTest.java
  chess-procjet/src/test/java/org/example/chess/pieces/PawnTest.java
  chess-procjet/src/test/java/org/example/piece/PawnTest.java
Labels: Step1-2

#37 [Lechros] step-2 체스판 생성
  src/main/chess/Board.java
  src/main/chess/piece/Color.java
  src/main/chess/piece/Pawn.java
  src/main/chess/piece/Piece.java
  src/main/piece/Pawn.java
  src/test/chess/BoardTest.java
  src/test/chess/piece/PieceTest.java
  src/test/piece/PawnTest.java
Labels: Step1-2

#38 [mirageoasis] step-1 체스 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/example/Main.java
  src/main/java/org/example/Pawn.java
  src/test/java/org/example/PawnTest.java
Labels: Step1-1

#39 [miiiinju1] step-2 체스판 생성
  src/main/java/chess/Board.java
  src/main/java/chess/Pawn.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-2

#40 [Hyeon-Uk] step-2 체스판 생성
  .gitignore
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/ChessPiece.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-2

#41 [Dr-KoKo] step-2 체스판 생성
  src/main/java/pe/goblin/chess/Main.java
  src/test/java/pe/goblin/chess/board/Board.java
  src/test/java/pe/goblin/chess/board/BoardTest.java
  src/test/java/pe/goblin/chess/board/ExceedPawnException.java
  src/test/java/pe/goblin/chess/pawn/Pawn.java
  src/test/java/pe/goblin/chess/pawn/PawnTest.java
  src/test/java/pe/goblin/pawn/Pawn.java
Labels: Step1-2

#42 [minseok-oh] step-2 체스판 생성
  .github/workflows/merge.yml
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-2

#44 [kariskan] step-3 체스판 초기화
  src/main/java/ChessApplication.java
  src/main/java/chess/Board.java
  src/main/java/chess/CommandType.java
  src/main/java/pieces/Color.java
  src/main/java/pieces/Empty.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step1-3

#45 [김규원] step-2 체스판 생성
  java-chess/src/main/java/org/example/character/Pawn.java
  java-chess/src/main/java/org/example/chess/Board.java
  java-chess/src/main/java/org/example/chess/pieces/Pawn.java
  java-chess/src/test/java/PawnTest.java
  java-chess/src/test/java/org/example/chess/BoardTest.java
  java-chess/src/test/java/org/example/chess/pieces/PawnTest.java
Labels: Step1-2

#46 [HyeonJun0530] step-2 체스판 생성
  .github/workflows/merge.yml
  src/main/java/chess/Board.java
  src/main/java/chess/piece/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PawnTest.java
Labels: Step1-2

#47 [huiseung] step-3 체스판 초기화
  chess/.gitignore
  chess/src/main/java/chess/Board.java
  chess/src/main/java/chess/ChessGame.java
  chess/src/main/java/pieces/PieceUnicode.java
  chess/src/test/java/chess/BoardTest.java
  chess/src/test/java/pieces/PawnTest.java
Labels: Step1-3

#48 [kimhyun5u] step-3 체스판 초기화
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-3

#49 [jcw1031] step-2 체스판 생성
  src/main/java/com/woopaca/javachess/chess/Board.java
  src/main/java/com/woopaca/javachess/chess/pieces/Pawn.java
  src/test/java/com/woopaca/javachess/chess/BoardTest.java
  src/test/java/com/woopaca/javachess/chess/pieces/PawnTest.java
Labels: Step1-2

#50 [yudonggeun] step-2 체스판 생성
  src/main/java/com/example/demo/context/Board.java
  src/main/java/com/example/demo/context/File.java
  src/main/java/com/example/demo/context/Rank.java
  src/main/java/com/example/demo/piece/Color.java
  src/main/java/com/example/demo/piece/Pawn.java
  src/test/java/com/example/demo/context/BoardTest.java
  src/test/java/com/example/demo/piece/PawnTest.java
Labels: Step1-2

#51 [hellomatia] step-2 체스판 생성
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/woowatechcamp/chess/Board.java
  src/main/java/com/woowatechcamp/chess/pieces/Color.java
  src/main/java/com/woowatechcamp/chess/pieces/Pawn.java
  src/test/java/com/woowatechcamp/chess/BoardTest.java
  src/test/java/com/woowatechcamp/chess/pieces/PawnTest.java
Labels: Step1-2

#52 [KoKimSS] step-2 체스판 생성
  woowa_camp_chess/src/main/java/org/example/chess/board/Board.java
  woowa_camp_chess/src/main/java/org/example/chess/pieces/Pawn.java
  woowa_camp_chess/src/test/java/org/example/board/BoardTest.java
  woowa_camp_chess/src/test/java/org/example/pieces/PawnTest.java
Labels: Step1-2

#53 [LuizyHub] step-3 체스판 초기화
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Main.java
  src/main/java/chess/piece/Pawn.java
  src/main/java/chess/piece/Piece.java
  src/main/java/chess/util/ChessPoint.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PawnTest.java
Labels: Step1-3

#54 [i960107] step-2 체스판 생성
  build.gradle
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-2

#55 [miiiinju1] step-3 체스판 초기화
  .gitignore
  .idea/.gitignore
  src/main/java/chess/Board.java
  src/main/java/chess/Main.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-3

#57 [Hyeon-Uk] step-3 체스판 초기화
  src/main/java/chess/Board.java
  src/main/java/chess/BoardGame.java
  src/main/java/chess/pieces/ChessPiece.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-3

#58 [bellringstar] step-3 체스판 초기화
  chess-procjet/src/main/java/org/example/Game.java
  chess-procjet/src/main/java/org/example/Main.java
  chess-procjet/src/main/java/org/example/chess/board/Board.java
  chess-procjet/src/main/java/org/example/chess/pieces/Pawn.java
  chess-procjet/src/test/java/org/example/chess/board/BoardTest.java
  chess-procjet/src/test/java/org/example/chess/pieces/PawnTest.java
Labels: Step1-3

#59 [june-777] step-2 체스판 생성
  .github/workflows/merge.yml
  src/main/java/woowa/camp/Pawn.java
  src/main/java/woowa/camp/chess/Board.java
  src/main/java/woowa/camp/pieces/Pawn.java
  src/test/java/woowa/camp/PawnTest.java
  src/test/java/woowa/camp/chess/BoardTest.java
  src/test/java/woowa/camp/pieces/PawnTest.java
Labels: Step1-2

#60 [hek-git] step-1 체스 프로젝트 시작
  .github/workflows/merge.yml
  .gitignore
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step1-1

#61 [kariskan] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/Rank.java
  src/main/java/pieces/Color.java
  src/main/java/pieces/Empty.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/PieceType.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step1-4

#62 [lass9436] step-2 체스판 생성
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  chess/src/test/java/Pawn.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/lass9436/Main.java
  src/test/java/chess/Board.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/Pawn.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-2

#63 [seminchoi] step-2 체스판 생성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/wootecamp/chess/Board.java
  src/main/java/wootecamp/chess/Pawn.java
  src/main/java/wootecamp/chess/pieces/Pawn.java
  src/test/java/wootecamp/chess/BoardTest.java
  src/test/java/wootecamp/chess/pieces/PawnTest.java
Labels: Step1-2

#64 [huiseung] step-4 모든 기물 배치하기
  chess/src/main/java/chess/Board.java
  chess/src/main/java/pieces/Pawn.java
  chess/src/main/java/pieces/Piece.java
  chess/src/main/java/pieces/PieceColor.java
  chess/src/main/java/pieces/PieceFactory.java
  chess/src/test/java/chess/BoardTest.java
  chess/src/test/java/pieces/PawnTest.java
  chess/src/test/java/pieces/PieceFactoryTest.java
  chess/src/test/java/pieces/PieceTest.java
Labels: Step1-4

#65 [chhs2131] step-2 체스판 생성
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Colors.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/PawnTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-2

#66 [이경민] step-3 체스판 초기화
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/enums/Symbol.java
  src/main/java/chess/pieces/values/Location.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/values/LocationTest.java
Labels: Step1-3

#67 [yudongguen] step-3 체스판 초기화
  src/main/java/com/example/demo/DemoApplication.java
  src/main/java/com/example/demo/context/Board.java
  src/main/java/com/example/demo/context/Game.java
  src/main/java/com/example/demo/handler/ChessHandler.java
  src/main/java/com/example/demo/piece/Pawn.java
  src/test/java/com/example/demo/context/BoardTest.java
  src/test/java/com/example/demo/handler/CliHandlerTest.java
  src/test/java/com/example/demo/piece/PawnTest.java
Labels: Step1-3

#68 [hseong3243] step-3 체스판 초기화
  src/main/java/com/seong/Main.java
  src/main/java/com/seong/chess/Board.java
  src/main/java/com/seong/chess/Column.java
  src/main/java/com/seong/chess/Point.java
  src/main/java/com/seong/chess/pieces/Pawn.java
  src/main/java/com/seong/chess/pieces/Piece.java
  src/test/java/com/seong/chess/BoardTest.java
  src/test/java/com/seong/chess/pieces/PawnTest.java
Labels: Step1-3

#69 [Dr-KoKo] step-3 체스판 초기화
  src/main/java/pe/goblin/chess/Main.java
  src/main/java/pe/goblin/chess/board/Board.java
  src/main/java/pe/goblin/chess/board/ExceedPawnException.java
  src/main/java/pe/goblin/chess/pawn/Pawn.java
  src/test/java/pe/goblin/chess/board/Board.java
  src/test/java/pe/goblin/chess/board/BoardTest.java
  src/test/java/pe/goblin/chess/pawn/Pawn.java
  src/test/java/pe/goblin/chess/pawn/PawnTest.java
Labels: Step1-3

#70 [hellomatia] step-3 체스판 초기화
  src/main/java/com/woowatechcamp/chess/Board.java
  src/main/java/com/woowatechcamp/chess/GameState.java
  src/main/java/com/woowatechcamp/chess/Main.java
  src/main/java/com/woowatechcamp/chess/pieces/Pawn.java
  src/test/java/com/woowatechcamp/chess/BoardTest.java
  src/test/java/com/woowatechcamp/chess/pieces/PawnTest.java
Labels: Step1-3

#71 [HiiWee] step-3 체스판 초기화
  src/main/java/com/wootecam/chess/Board.java
  src/main/java/com/wootecam/chess/ChessApplication.java
  src/main/java/com/wootecam/chess/pieces/Pawn.java
  src/test/java/com/wootecam/chess/BoardTest.java
  src/test/java/com/wootecam/chess/pieces/PawnTest.java
Labels: Step1-3

#72 [minseok-oh] step-3 체스판 초기화
  src/main/java/chess/Board.java
  src/main/java/chess/Main.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-3

#73 [Hyeon-Uk] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/ChessPiece.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/PieceTypes.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/utils/StringUtilsTest.java
Labels: Step1-4

#74 [KoKimSS] step-3 체스판 초기화
  woowa_camp_chess/src/main/java/org/example/Main.java
  woowa_camp_chess/src/main/java/org/example/chess/board/Board.java
  woowa_camp_chess/src/main/java/org/example/chess/pieces/Pawn.java
  woowa_camp_chess/src/main/java/org/example/chess/pieces/Piece.java
  woowa_camp_chess/src/test/java/org/example/board/BoardTest.java
  woowa_camp_chess/src/test/java/org/example/pieces/PawnTest.java
Labels: Step1-3

#75 [LuizyHub] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/piece/Bishop.java
  src/main/java/chess/piece/King.java
  src/main/java/chess/piece/Knight.java
  src/main/java/chess/piece/Pawn.java
  src/main/java/chess/piece/Piece.java
  src/main/java/chess/piece/Queen.java
  src/main/java/chess/piece/Rook.java
  src/main/java/chess/util/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PawnTest.java
  src/test/java/chess/piece/PieceTest.java
Labels: Step1-4

#77 [minnim1010] step-3 체스판 초기화
  src/main/java/com/wootecam/chess/Board.java
  src/main/java/com/wootecam/chess/ChessBoard.java
  src/main/java/com/wootecam/chess/ChessGame.java
  src/main/java/com/wootecam/chess/ChessGameManager.java
  src/main/java/com/wootecam/chess/Color.java
  src/main/java/com/wootecam/chess/Reader.java
  src/main/java/com/wootecam/chess/pieces/Color.java
  src/main/java/com/wootecam/chess/pieces/Pawn.java
  src/main/java/com/wootecam/chess/pieces/PieceRepresentation.java
  src/test/java/com/wootecam/chess/BoardTest.java
  src/test/java/com/wootecam/chess/pieces/PawnTest.java
Labels: Step1-3

#78 [chhs2131] step-3 체스판 초기화
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Representations.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-3

#79 [miiiinju1] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/utils/StringUtilsTest.java
Labels: Step1-4

#80 [jcw1031] step-3 체스판 초기화
  src/main/java/com/woopaca/javachess/chess/Board.java
  src/main/java/com/woopaca/javachess/chess/ChessGame.java
  src/main/java/com/woopaca/javachess/chess/pieces/Pawn.java
  src/test/java/com/woopaca/javachess/chess/BoardTest.java
  src/test/java/com/woopaca/javachess/chess/pieces/PawnTest.java
Labels: Step1-3

#81 [i960107] step-3 체스판 초기화
  src/main/java/chess/Application.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-3

#82 [HyeonJun0530] Step-3 체스판 초기화
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Main.java
  src/main/java/chess/config/AppConfig.java
  src/main/java/chess/piece/Pawn.java
  src/main/java/chess/piece/PieceColor.java
  src/main/java/chess/piece/PieceRepresentation.java
  src/main/java/chess/piece/Position.java
  src/main/java/chess/piece/Type.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PawnTest.java
Labels: Step1-3

#83 [lass9436] step-3 체스판 초기화
  src/test/java/Main.java
  src/test/java/chess/Board.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/Pawn.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-3

#86 [hseong3243] step-4 모든 기물 배치하기
  src/main/java/com/seong/Main.java
  src/main/java/com/seong/chess/Board.java
  src/main/java/com/seong/chess/Column.java
  src/main/java/com/seong/chess/Point.java
  src/main/java/com/seong/chess/Position.java
  src/main/java/com/seong/chess/pieces/Pawn.java
  src/main/java/com/seong/chess/pieces/Piece.java
  src/main/java/com/seong/chess/utils/StringUtils.java
  src/test/java/com/seong/chess/BoardTest.java
  src/test/java/com/seong/chess/pieces/PawnTest.java
  src/test/java/com/seong/chess/pieces/PieceTest.java
  src/test/java/com/seong/chess/utils/StringUtilsTest.java
Labels: Step1-4

#88 [이경민] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-4

#89 [hellomatia] step-4 모든 기물 배치하기
  src/main/java/com/woowatechcamp/chess/Board.java
  src/main/java/com/woowatechcamp/chess/pieces/Color.java
  src/main/java/com/woowatechcamp/chess/pieces/Pawn.java
  src/main/java/com/woowatechcamp/chess/pieces/Piece.java
  src/main/java/com/woowatechcamp/chess/pieces/Type.java
  src/main/java/com/woowatechcamp/utils/StringUtils.java
  src/test/java/com/woowatechcamp/chess/BoardTest.java
  src/test/java/com/woowatechcamp/chess/pieces/PawnTest.java
  src/test/java/com/woowatechcamp/chess/pieces/PieceTest.java
Labels: Step1-4

#90 [seminchoi] step-3 체스판 초기화
  src/main/java/wootecamp/chess/Board.java
  src/main/java/wootecamp/chess/Main.java
  src/main/java/wootecamp/chess/pieces/Pawn.java
  src/test/java/wootecamp/chess/BoardTest.java
  src/test/java/wootecamp/chess/pieces/PawnTest.java
Labels: Step1-3

#91 [minseok-oh] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/Main.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-4

#92 [bellringstar] step-4 모든 기물 배치하기
  chess-procjet/src/main/java/org/example/chess/board/Board.java
  chess-procjet/src/main/java/org/example/chess/board/Point.java
  chess-procjet/src/main/java/org/example/chess/pieces/Pawn.java
  chess-procjet/src/main/java/org/example/chess/pieces/Piece.java
  chess-procjet/src/main/java/org/example/chess/pieces/PieceFactory.java
  chess-procjet/src/main/java/org/example/chess/pieces/PieceName.java
  chess-procjet/src/main/java/org/example/utils/StringUtils.java
  chess-procjet/src/test/java/org/example/chess/board/BoardTest.java
  chess-procjet/src/test/java/org/example/chess/pieces/PawnTest.java
  chess-procjet/src/test/java/org/example/chess/pieces/PieceTest.java
Labels: Step1-4

#94 [kariskan] step5 - 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/Position.java
  src/main/java/chess/Rank.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/PieceType.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step1-5

#76 [김규원] step-3 체스판 초기화
  java-chess/src/main/java/org/example/Main.java
  java-chess/src/main/java/org/example/chess/Board.java
  java-chess/src/main/java/org/example/chess/pieces/Pawn.java
  java-chess/src/main/java/org/example/chess/pieces/Piece.java
  java-chess/src/main/java/org/example/chess/pieces/global/Position.java
  java-chess/src/main/java/org/example/utils/StringUtils.java
  java-chess/src/test/java/org/example/chess/BoardTest.java
  java-chess/src/test/java/org/example/chess/pieces/PawnTest.java
  java-chess/src/test/java/org/example/chess/pieces/PieceTest.java
Labels: Step1-3

#95 [Lechros] step-3 체스판 초기화
  src/main/chess/ChessBoard.java
  src/main/chess/ChessStrings.java
  src/main/chess/ConsoleGame.java
  src/main/chess/Game.java
  src/main/chess/piece/Pawn.java
  src/main/chess/piece/Piece.java
  src/test/chess/BoardTest.java
  src/test/chess/ChessBoardTest.java
Labels: Step1-3

#96 Hek git
  .gitignore
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/BoardTest.java
  src/test/java/PawnTest.java
Labels: Step1-2

#97 [huiseung] step-5 기물 위치 부여 및 점수계산
  chess/src/main/java/chess/Board.java
  chess/src/main/java/chess/Position.java
  chess/src/main/java/chess/Rank.java
  chess/src/main/java/pieces/Piece.java
  chess/src/main/java/pieces/PieceColor.java
  chess/src/main/java/pieces/PieceDescriptor.java
  chess/src/main/java/pieces/PieceFactory.java
  chess/src/main/java/pieces/PieceType.java
  chess/src/main/java/pieces/PieceUnicode.java
  chess/src/main/java/util/Order.java
  chess/src/test/java/chess/BoardTest.java
  chess/src/test/java/pieces/PieceFactoryTest.java
  chess/src/test/java/pieces/PieceTest.java
Labels: Step1-5

#98 [minnim1010] step-4 모든 기물 배치하기
  src/main/java/com/wootecam/chess/Board.java
  src/main/java/com/wootecam/chess/board/Board.java
  src/main/java/com/wootecam/chess/board/ChessBoard.java
  src/main/java/com/wootecam/chess/game/ChessGame.java
  src/main/java/com/wootecam/chess/game/ChessGameManager.java
  src/main/java/com/wootecam/chess/pieces/Bishop.java
  src/main/java/com/wootecam/chess/pieces/Color.java
  src/main/java/com/wootecam/chess/pieces/King.java
  src/main/java/com/wootecam/chess/pieces/Knight.java
  src/main/java/com/wootecam/chess/pieces/Pawn.java
  src/main/java/com/wootecam/chess/pieces/Piece.java
  src/main/java/com/wootecam/chess/pieces/PieceRepresentation.java
  src/main/java/com/wootecam/chess/pieces/PieceType.java
  src/main/java/com/wootecam/chess/pieces/Queen.java
  src/main/java/com/wootecam/chess/pieces/Rook.java
  src/main/java/com/wootecam/chess/utils/StringUtils.java
  src/test/java/com/wootecam/chess/BoardTest.java
  src/test/java/com/wootecam/chess/pieces/PawnTest.java
  src/test/java/com/wootecam/chess/pieces/PieceTest.java
Labels: Step1-4

#101 [HiiWee] step-4 모든 기물 배치하기
  src/main/java/com/wootecam/chess/Board.java
  src/main/java/com/wootecam/chess/ChessApplication.java
  src/main/java/com/wootecam/chess/pieces/Pawn.java
  src/main/java/com/wootecam/chess/pieces/Piece.java
  src/main/java/com/wootecam/chess/utils/StringUtils.java
  src/test/java/com/wootecam/chess/BoardTest.java
  src/test/java/com/wootecam/chess/pieces/PawnTest.java
  src/test/java/com/wootecam/chess/pieces/PiecesTest.java
Labels: Step1-4

#102 [jcw1031] step-4 모든 기물 배치하기
  src/main/java/com/woopaca/javachess/chess/Board.java
  src/main/java/com/woopaca/javachess/chess/pieces/Pawn.java
  src/main/java/com/woopaca/javachess/chess/pieces/Piece.java
  src/main/java/com/woopaca/javachess/chess/pieces/PieceType.java
  src/main/java/com/woopaca/javachess/chess/utils/StringUtils.java
  src/test/java/com/woopaca/javachess/chess/BoardTest.java
  src/test/java/com/woopaca/javachess/chess/pieces/PawnTest.java
  src/test/java/com/woopaca/javachess/chess/pieces/PieceTest.java
Labels: Step1-4

#99 [yudonggeun] step5 - 기물 위치 부여 및 점수계산
  src/main/java/com/example/demo/context/Board.java
  src/main/java/com/example/demo/piece/Bishop.java
  src/main/java/com/example/demo/piece/King.java
  src/main/java/com/example/demo/piece/Knight.java
  src/main/java/com/example/demo/piece/Pawn.java
  src/main/java/com/example/demo/piece/Piece.java
  src/main/java/com/example/demo/piece/Queen.java
  src/main/java/com/example/demo/piece/Rook.java
  src/test/java/com/example/demo/context/BoardTest.java
  src/test/java/com/example/demo/piece/BishopTest.java
  src/test/java/com/example/demo/piece/KingTest.java
  src/test/java/com/example/demo/piece/KnightTest.java
  src/test/java/com/example/demo/piece/PawnTest.java
  src/test/java/com/example/demo/piece/QueenTest.java
  src/test/java/com/example/demo/piece/RookTest.java
Labels: Step1-5

#100 [LuizyHub] ster-5 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/piece/Bishop.java
  src/main/java/chess/piece/King.java
  src/main/java/chess/piece/Knight.java
  src/main/java/chess/piece/Pawn.java
  src/main/java/chess/piece/Piece.java
  src/main/java/chess/piece/Queen.java
  src/main/java/chess/piece/Rook.java
  src/main/java/chess/util/ChessPoint.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PawnTest.java
  src/test/java/chess/piece/PieceTest.java
Labels: Step1-5

#103 [KoKimSS] step-4 모든 기물 배치하기
  woowa_camp_chess/src/main/java/org/example/Main.java
  woowa_camp_chess/src/main/java/org/example/chess/board/Board.java
  woowa_camp_chess/src/main/java/org/example/chess/pieces/Pawn.java
  woowa_camp_chess/src/main/java/org/example/chess/pieces/Piece.java
  woowa_camp_chess/src/main/java/org/example/chess/pieces/PieceType.java
  woowa_camp_chess/src/main/java/org/example/utils/StringUtils.java
  woowa_camp_chess/src/test/java/org/example/board/BoardTest.java
  woowa_camp_chess/src/test/java/org/example/pieces/PawnTest.java
  woowa_camp_chess/src/test/java/org/example/pieces/PieceTest.java
Labels: Step1-4

#104 [HyeonJun0530] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/BoardFactory.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/File.java
  src/main/java/chess/Rank.java
  src/main/java/chess/piece/Bishop.java
  src/main/java/chess/piece/King.java
  src/main/java/chess/piece/Knight.java
  src/main/java/chess/piece/Pawn.java
  src/main/java/chess/piece/Piece.java
  src/main/java/chess/piece/PieceRepresentation.java
  src/main/java/chess/piece/Position.java
  src/main/java/chess/piece/Queen.java
  src/main/java/chess/piece/Rook.java
  src/main/java/chess/piece/Type.java
  src/main/java/chess/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PawnTest.java
  src/test/java/chess/piece/PieceTest.java
Labels: Step1-4

#105 [kimhyun5u, seungh1024] step-4,5 모든 기물 배치하기, 기물 위치 부여 및 점수 계산
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/Position.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-4, Step1-5

#109 [tidavid1] ster-5 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/pieces/enums/Type.java
  src/main/java/chess/pieces/values/Location.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/pieces/values/LocationTest.java
Labels: Step1-5

#110 [Dr-KoKo] step-4 모든 기물 배치하기
  src/main/java/pe/goblin/chess/board/Board.java
  src/main/java/pe/goblin/chess/pawn/Pawn.java
  src/main/java/pe/goblin/chess/piece/Piece.java
  src/main/java/pe/goblin/chess/utils/StringUtils.java
  src/test/java/pe/goblin/chess/board/BoardTest.java
  src/test/java/pe/goblin/chess/pawn/PawnTest.java
  src/test/java/pe/goblin/chess/piece/PieceTest.java
Labels: Step1-4

#107 [seminchoi] step-4 모든 기물 배치하기
  src/main/java/wootecamp/chess/Board.java
  src/main/java/wootecamp/chess/Main.java
  src/main/java/wootecamp/chess/Rank.java
  src/main/java/wootecamp/chess/pieces/Pawn.java
  src/main/java/wootecamp/chess/pieces/Piece.java
  src/main/java/wootecamp/chess/util/StringUtils.java
  src/test/java/wootecamp/chess/BoardTest.java
  src/test/java/wootecamp/chess/pieces/PawnTest.java
  src/test/java/wootecamp/chess/pieces/PieceTest.java
Labels: Step1-4

#112 [lass9436] step-4 모든 기물 배치하기
  src/test/java/Main.java
  src/test/java/chess/Board.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/Pawn.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/Piece.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/utils/StringUtils.java
Labels: Step1-4

#113 [hek-git] step-3 체스판 초기화
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGameManager.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/BoardTest.java
  src/test/java/PawnTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step1-3

#114 [minseok-oh] step-5 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Color.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Position.java
  src/main/java/chess/pieces/Rank.java
  src/main/java/chess/pieces/Type.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-5

#115 [Hyeon-Uk] step-5 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/ChessPiece.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/PieceTypes.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-5

#116 [hellomatia] step-5 기물 위치 부여 및 점수계산
  src/main/java/com/woowatechcamp/chess/Board.java
  src/main/java/com/woowatechcamp/chess/GameState.java
  src/main/java/com/woowatechcamp/chess/Main.java
  src/main/java/com/woowatechcamp/chess/Rank.java
  src/main/java/com/woowatechcamp/chess/pieces/Color.java
  src/main/java/com/woowatechcamp/chess/pieces/Piece.java
  src/main/java/com/woowatechcamp/chess/pieces/Type.java
  src/main/java/com/woowatechcamp/utils/StringUtils.java
  src/test/java/com/woowatechcamp/chess/BoardTest.java
  src/test/java/com/woowatechcamp/chess/pieces/PieceTest.java
Labels: Step1-5

#117 [miiiinju1] ster-5 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/Main.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/board/RankTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-5

#118 [hseong3243] step-5 기물 위치 부여 및 점수계산
  src/main/java/com/seong/chess/Board.java
  src/main/java/com/seong/chess/Column.java
  src/main/java/com/seong/chess/Position.java
  src/main/java/com/seong/chess/Rank.java
  src/main/java/com/seong/chess/pieces/Bishop.java
  src/main/java/com/seong/chess/pieces/Blank.java
  src/main/java/com/seong/chess/pieces/King.java
  src/main/java/com/seong/chess/pieces/Knight.java
  src/main/java/com/seong/chess/pieces/Pawn.java
  src/main/java/com/seong/chess/pieces/Piece.java
  src/main/java/com/seong/chess/pieces/Queen.java
  src/main/java/com/seong/chess/pieces/Rook.java
  src/test/java/com/seong/chess/BoardTest.java
  src/test/java/com/seong/chess/pieces/PieceTest.java
Labels: Step1-5

#119 [HyeonJun0530] step-5 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/BoardFactory.java
  src/main/java/chess/File.java
  src/main/java/chess/Rank.java
  src/main/java/chess/piece/Blank.java
  src/main/java/chess/piece/PieceColor.java
  src/main/java/chess/piece/PieceRepresentation.java
  src/main/java/chess/piece/Position.java
  src/main/java/chess/piece/Type.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PieceTest.java
Labels: Step1-5

#120 [Lechros] step-5 기물 위치 부여 및 점수계산
  src/main/chess/Board.java
  src/main/chess/Position.java
  src/main/chess/piece/Bishop.java
  src/main/chess/piece/Color.java
  src/main/chess/piece/King.java
  src/main/chess/piece/Knight.java
  src/main/chess/piece/Pawn.java
  src/main/chess/piece/Piece.java
  src/main/chess/piece/Queen.java
  src/main/chess/piece/Rook.java
  src/test/chess/BoardTest.java
  src/test/chess/piece/PieceTest.java
Labels: Step1-5

#121 [bellringstar] step-5 기물 위치 부여 및 점수계산
  .DS_Store
  chess-procjet/.idea/checkstyle-idea.xml
  chess-procjet/.idea/gradle.xml
  chess-procjet/.idea/misc.xml
  chess-procjet/.idea/uiDesigner.xml
  chess-procjet/.idea/vcs.xml
  chess-procjet/.idea/workspace.xml
  chess-procjet/src/main/java/org/example/chess/board/Board.java
  chess-procjet/src/main/java/org/example/chess/board/Point.java
  chess-procjet/src/main/java/org/example/chess/board/Position.java
  chess-procjet/src/main/java/org/example/chess/board/sort/AscendingPieceComparator.java
  chess-procjet/src/main/java/org/example/chess/board/sort/DescendingPieceComparator.java
  chess-procjet/src/main/java/org/example/chess/board/sort/PieceComparator.java
  chess-procjet/src/main/java/org/example/chess/board/sort/PieceComparatorFactory.java
  chess-procjet/src/main/java/org/example/chess/pieces/Color.java
  chess-procjet/src/main/java/org/example/chess/pieces/Piece.java
  chess-procjet/src/main/java/org/example/chess/pieces/PieceFactory.java
  chess-procjet/src/main/java/org/example/chess/pieces/PieceName.java
  chess-procjet/src/test/java/org/example/chess/board/BoardTest.java
  chess-procjet/src/test/java/org/example/chess/board/RankTest.java
  chess-procjet/src/test/java/org/example/chess/pieces/PieceTest.java
Labels: Step1-5

#122 [june-777] step-4 모든 기물 배치하기
  src/main/java/woowa/camp/ChessGameStarter.java
  src/main/java/woowa/camp/chess/Board.java
  src/main/java/woowa/camp/pieces/Color.java
  src/main/java/woowa/camp/pieces/Pawn.java
  src/main/java/woowa/camp/pieces/Piece.java
  src/main/java/woowa/camp/utils/StringUtils.java
  src/test/java/woowa/camp/chess/BoardTest.java
  src/test/java/woowa/camp/pieces/PawnTest.java
  src/test/java/woowa/camp/pieces/PieceTest.java
Labels: Step1-4

#123 [KoKimSS] step-5 기물 위치 부여 및 점수계산
  woowa_camp_chess/src/main/java/org/example/Main.java
  woowa_camp_chess/src/main/java/org/example/chess/board/Board.java
  woowa_camp_chess/src/main/java/org/example/chess/board/Position.java
  woowa_camp_chess/src/main/java/org/example/chess/pieces/Piece.java
  woowa_camp_chess/src/main/java/org/example/chess/pieces/PieceType.java
  woowa_camp_chess/src/test/java/org/example/board/BoardTest.java
  woowa_camp_chess/src/test/java/org/example/pieces/PieceTest.java
Labels: Step1-5

#124 [lass9436] step-5 기물 위치 부여 및 점수 계산
  src/test/java/chess/Board.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/Position.java
  src/test/java/chess/pieces/Piece.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-5

#126 [jcw1031] step-5 기물 위치 부여 및 점수계산
  src/main/java/com/woopaca/javachess/ChessGame.java
  src/main/java/com/woopaca/javachess/chess/Board.java
  src/main/java/com/woopaca/javachess/chess/Position.java
  src/main/java/com/woopaca/javachess/chess/Rank.java
  src/main/java/com/woopaca/javachess/chess/pieces/Piece.java
  src/main/java/com/woopaca/javachess/chess/pieces/PieceType.java
  src/main/java/com/woopaca/javachess/pieces/Color.java
  src/main/java/com/woopaca/javachess/pieces/Piece.java
  src/main/java/com/woopaca/javachess/pieces/Type.java
  src/main/java/com/woopaca/javachess/utils/StringUtils.java
  src/test/java/com/woopaca/javachess/chess/BoardTest.java
  src/test/java/com/woopaca/javachess/chess/pieces/PieceTest.java
  src/test/java/com/woopaca/javachess/pieces/PieceTest.java
Labels: Step1-5

#127 [hellomatia] step-6 기물 이동 구현
  src/main/java/com/woowatechcamp/chess/Board.java
  src/main/java/com/woowatechcamp/chess/GameCommand.java
  src/main/java/com/woowatechcamp/chess/GameState.java
  src/main/java/com/woowatechcamp/chess/Main.java
  src/main/java/com/woowatechcamp/chess/Rank.java
  src/main/java/com/woowatechcamp/chess/pieces/Bishop.java
  src/main/java/com/woowatechcamp/chess/pieces/Blank.java
  src/main/java/com/woowatechcamp/chess/pieces/King.java
  src/main/java/com/woowatechcamp/chess/pieces/Knight.java
  src/main/java/com/woowatechcamp/chess/pieces/Pawn.java
  src/main/java/com/woowatechcamp/chess/pieces/Piece.java
  src/main/java/com/woowatechcamp/chess/pieces/PieceFactory.java
  src/main/java/com/woowatechcamp/chess/pieces/Position.java
  src/main/java/com/woowatechcamp/chess/pieces/Queen.java
  src/main/java/com/woowatechcamp/chess/pieces/Rook.java
  src/test/java/com/woowatechcamp/chess/BoardTest.java
  src/test/java/com/woowatechcamp/chess/pieces/BishopTest.java
  src/test/java/com/woowatechcamp/chess/pieces/KingTest.java
  src/test/java/com/woowatechcamp/chess/pieces/KnightTest.java
  src/test/java/com/woowatechcamp/chess/pieces/PawnTest.java
  src/test/java/com/woowatechcamp/chess/pieces/PieceTest.java
  src/test/java/com/woowatechcamp/chess/pieces/QueenTest.java
  src/test/java/com/woowatechcamp/chess/pieces/RookTest.java
Labels: Step1-6

#128 [chhs2131] step-5 기물 위치 부여 및 점수 계산
  src/main/java/ChessGame.java
  src/main/java/chess/Board.java
  src/main/java/chess/Position.java
  src/main/java/chess/Rank.java
  src/main/java/chess/calculator/OrderBy.java
  src/main/java/chess/calculator/ScoreUtils.java
  src/main/java/chess/pieces/Color.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Representation.java
  src/main/java/chess/pieces/Representations.java
  src/main/java/utils/RankMaker.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/PositionTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-5

#129 [hek-git] step-1-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGameManager.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-4

#130 [minnim1010] step-5 기물 위치 부여 및 점수 계산
  src/main/java/com/wootecam/chess/board/Board.java
  src/main/java/com/wootecam/chess/board/BoardInitializer.java
  src/main/java/com/wootecam/chess/board/ChessBoard.java
  src/main/java/com/wootecam/chess/board/Position.java
  src/main/java/com/wootecam/chess/common/Order.java
  src/main/java/com/wootecam/chess/common/Reader.java
  src/main/java/com/wootecam/chess/game/ChessGame.java
  src/main/java/com/wootecam/chess/game/ChessGameManager.java
  src/main/java/com/wootecam/chess/pieces/Color.java
  src/main/java/com/wootecam/chess/pieces/Piece.java
  src/main/java/com/wootecam/chess/pieces/PieceRepresentation.java
  src/main/java/com/wootecam/chess/pieces/PieceType.java
  src/test/java/com/wootecam/chess/BoardTest.java
  src/test/java/com/wootecam/chess/Fixture.java
  src/test/java/com/wootecam/chess/board/BoardInitializerTest.java
  src/test/java/com/wootecam/chess/board/BoardTest.java
  src/test/java/com/wootecam/chess/board/PositionTest.java
  src/test/java/com/wootecam/chess/pieces/PieceTest.java
Labels: Step1-5

#131 [mirageoasis] step-5 기물 위치 부여 및 점수 계산
  src/main/java/org/example/Main.java
  src/main/java/org/example/chess/Board.java
  src/main/java/org/example/chess/Position.java
  src/main/java/org/example/pieces/Piece.java
  src/test/java/org/example/chess/BoardTest.java
  src/test/java/org/example/pieces/PieceTest.java
Labels: Step1-5

#132 [HiiWee] step-5 기물 위치 부여 및 점수계산
  src/main/java/com/wootecam/chess/Board.java
  src/main/java/com/wootecam/chess/ChessApplication.java
  src/main/java/com/wootecam/chess/CoordinatesExtractor.java
  src/main/java/com/wootecam/chess/pieces/Color.java
  src/main/java/com/wootecam/chess/pieces/Piece.java
  src/main/java/com/wootecam/chess/pieces/Rank.java
  src/main/java/com/wootecam/chess/pieces/Type.java
  src/main/java/com/wootecam/chess/utils/StringUtils.java
  src/test/java/com/wootecam/chess/BoardTest.java
  src/test/java/com/wootecam/chess/pieces/PiecesTest.java
  src/test/java/com/wootecam/chess/pieces/RankTest.java
  src/test/java/com/wootecam/chess/pieces/TypeTest.java
Labels: Step1-5

#133 [huiseung] step-6 기물 이동 구현, step-7 예외 처리
  chess/.idea/gradle.xml
  chess/READMe.md
  chess/src/main/java/chess/Board.java
  chess/src/main/java/chess/BoardArea.java
  chess/src/main/java/chess/ChessGame.java
  chess/src/main/java/chess/Main.java
  chess/src/main/java/chess/Position.java
  chess/src/main/java/chess/Rank.java
  chess/src/main/java/exception/InvalidMoveException.java
  chess/src/main/java/exception/OutOfBoardException.java
  chess/src/main/java/pieces/Bishop.java
  chess/src/main/java/pieces/Blank.java
  chess/src/main/java/pieces/King.java
  chess/src/main/java/pieces/Knight.java
  chess/src/main/java/pieces/Pawn.java
  chess/src/main/java/pieces/Piece.java
  chess/src/main/java/pieces/PieceFactory.java
  chess/src/main/java/pieces/PieceUnicode.java
  chess/src/main/java/pieces/Queen.java
  chess/src/main/java/pieces/Rook.java
  chess/src/test/java/chess/BoardTest.java
  chess/src/test/java/chess/ChessGameTest.java
  chess/src/test/java/pieces/BishopTest.java
  chess/src/test/java/pieces/KingTest.java
  chess/src/test/java/pieces/KnightTest.java
  chess/src/test/java/pieces/PieceDescriptorTest.java
  chess/src/test/java/pieces/PieceFactoryTest.java
  chess/src/test/java/pieces/PieceTest.java
  chess/src/test/java/pieces/QueenTest.java
  chess/src/test/java/pieces/RookTest.java
Labels: Step1-6, Step1-7

#134 [kariskan] step-6 기물 이동 구현
  src/main/java/ChessApplication.java
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Command.java
  src/main/java/chess/CommandType.java
  src/main/java/chess/Direction.java
  src/main/java/chess/Position.java
  src/main/java/chess/Rank.java
  src/main/java/chess/Ranks.java
  src/main/java/pieces/Color.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/PieceType.java
  src/main/java/utils/MathUtils.java
  src/main/java/utils/StringUtils.java
  src/main/java/view/InputView.java
  src/main/java/view/OutputView.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step1-6

#136 [seminchoi] step-5 기물 위치 부여 및 점수계산
  src/main/java/wootecamp/chess/Board.java
  src/main/java/wootecamp/chess/BoardPosition.java
  src/main/java/wootecamp/chess/PieceComparator.java
  src/main/java/wootecamp/chess/Rank.java
  src/main/java/wootecamp/chess/pieces/Piece.java
  src/test/java/wootecamp/chess/BoardTest.java
  src/test/java/wootecamp/chess/RankTest.java
  src/test/java/wootecamp/chess/pieces/PieceTest.java
Labels: Step1-5

#137 [kkyu0718] step-5 기물 위치 부여 및 점수계산
  .gitignore
  java-chess/src/main/java/org/example/chess/Board.java
  java-chess/src/main/java/org/example/chess/pieces/Piece.java
  java-chess/src/main/java/org/example/chess/pieces/global/Order.java
  java-chess/src/main/java/org/example/chess/pieces/global/Position.java
  java-chess/src/test/java/org/example/chess/BoardTest.java
Labels: Step1-5

#138 [i960107] step-5 기물 위치 부여 및 점수계산
  src/main/java/chess/Application.java
  src/main/java/chess/Board.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/calculator/DefaultPointCalculateStrategy.java
  src/main/java/chess/calculator/PointCalculateStrategy.java
  src/main/java/chess/calculator/PointCalculator.java
  src/main/java/chess/calculator/SameFilePawnPointCalculateStrategy.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Position.java
  src/main/java/chess/sorter/Direction.java
  src/main/java/chess/sorter/PointSorter.java
  src/main/java/chess/sorter/Sorter.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/PositionTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-5

#139 [kariskan] step-7 예외 처리
  src/main/java/ChessApplication.java
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Command.java
  src/main/java/chess/CommandType.java
  src/main/java/chess/Direction.java
  src/main/java/chess/Position.java
  src/main/java/pieces/Color.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/PieceType.java
  src/main/java/utils/StringUtils.java
  src/main/java/view/InputView.java
  src/main/java/view/OutputView.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step1-7

#140 [Lechros] step-6 기물 이동 구현
  src/main/chess/Board.java
  src/main/chess/BoardContext.java
  src/main/chess/BoardContextImpl.java
  src/main/chess/Game.java
  src/main/chess/Offset.java
  src/main/chess/Position.java
  src/main/chess/piece/Bishop.java
  src/main/chess/piece/King.java
  src/main/chess/piece/Knight.java
  src/main/chess/piece/Pawn.java
  src/main/chess/piece/Piece.java
  src/main/chess/piece/Queen.java
  src/main/chess/piece/Rook.java
  src/test/chess/BoardTest.java
  src/test/chess/BoardUtils.java
  src/test/chess/OffsetTest.java
  src/test/chess/piece/BishopTest.java
  src/test/chess/piece/KingTest.java
  src/test/chess/piece/KnightTest.java
  src/test/chess/piece/PawnTest.java
  src/test/chess/piece/PieceTest.java
  src/test/chess/piece/PieceUtils.java
  src/test/chess/piece/QueenTest.java
  src/test/chess/piece/RookTest.java
Labels: Step1-6

#141 [miiiinju1] step-6 기물 이동 구현
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Main.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Coordinate.java
  src/main/java/chess/board/PointCalculator.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/view/ChessView.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/board/CoordinateTest.java
  src/test/java/chess/board/PointCalculatorTest.java
  src/test/java/chess/board/RankTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/BlankTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
  src/test/java/chess/view/ChessViewTest.java
Labels: Step1-6

#142 [tidavid1] step-7 예외 처리
  src/main/java/java_chess/ChessApplication.java
  src/main/java/java_chess/application/ChessGame.java
  src/main/java/java_chess/application/ChessView.java
  src/main/java/java_chess/chess/Board.java
  src/main/java/java_chess/chess/pieces/Bishop.java
  src/main/java/java_chess/chess/pieces/Blank.java
  src/main/java/java_chess/chess/pieces/King.java
  src/main/java/java_chess/chess/pieces/Knight.java
  src/main/java/java_chess/chess/pieces/Pawn.java
  src/main/java/java_chess/chess/pieces/Piece.java
  src/main/java/java_chess/chess/pieces/Queen.java
  src/main/java/java_chess/chess/pieces/Rook.java
  src/test/java/java_chess/application/ChessGameTest.java
  src/test/java/java_chess/application/ChessViewTest.java
  src/test/java/java_chess/chess/BoardTest.java
Labels: Step1-7

#143 [hseong3243] step-6 기물 이동 구현
  src/main/java/com/seong/Main.java
  src/main/java/com/seong/chess/Board.java
  src/main/java/com/seong/chess/ChessGame.java
  src/main/java/com/seong/chess/Position.java
  src/main/java/com/seong/chess/pieces/Bishop.java
  src/main/java/com/seong/chess/pieces/Blank.java
  src/main/java/com/seong/chess/pieces/Direction.java
  src/main/java/com/seong/chess/pieces/King.java
  src/main/java/com/seong/chess/pieces/Knight.java
  src/main/java/com/seong/chess/pieces/Pawn.java
  src/main/java/com/seong/chess/pieces/Piece.java
  src/main/java/com/seong/chess/pieces/Queen.java
  src/main/java/com/seong/chess/pieces/Rook.java
  src/test/java/com/seong/chess/BoardTest.java
  src/test/java/com/seong/chess/ChessGameTest.java
  src/test/java/com/seong/chess/PositionTest.java
  src/test/java/com/seong/chess/pieces/BishopTest.java
  src/test/java/com/seong/chess/pieces/KingTest.java
  src/test/java/com/seong/chess/pieces/KnightTest.java
  src/test/java/com/seong/chess/pieces/PawnTest.java
  src/test/java/com/seong/chess/pieces/QueenTest.java
  src/test/java/com/seong/chess/pieces/RookTest.java
Labels: Step1-6

#144 [Lechros] step-7 예외 처리
  src/main/chess/Board.java
  src/main/chess/ConsoleGame.java
  src/main/chess/Game.java
Labels: Step1-7

#145 [hellomatia] step-7 예외 처리
  src/main/java/com/woowatechcamp/chess/Board.java
  src/main/java/com/woowatechcamp/chess/ChessGame.java
  src/main/java/com/woowatechcamp/chess/Main.java
  src/main/java/com/woowatechcamp/chess/pieces/Bishop.java
  src/main/java/com/woowatechcamp/chess/pieces/Blank.java
  src/main/java/com/woowatechcamp/chess/pieces/Direction.java
  src/main/java/com/woowatechcamp/chess/pieces/King.java
  src/main/java/com/woowatechcamp/chess/pieces/Knight.java
  src/main/java/com/woowatechcamp/chess/pieces/Pawn.java
  src/main/java/com/woowatechcamp/chess/pieces/Piece.java
  src/main/java/com/woowatechcamp/chess/pieces/Position.java
  src/main/java/com/woowatechcamp/chess/pieces/Queen.java
  src/main/java/com/woowatechcamp/chess/pieces/Rook.java
  src/test/java/com/woowatechcamp/chess/ChessGameTest.java
  src/test/java/com/woowatechcamp/chess/pieces/BishopTest.java
  src/test/java/com/woowatechcamp/chess/pieces/KingTest.java
  src/test/java/com/woowatechcamp/chess/pieces/KnightTest.java
  src/test/java/com/woowatechcamp/chess/pieces/PawnTest.java
  src/test/java/com/woowatechcamp/chess/pieces/PieceTest.java
  src/test/java/com/woowatechcamp/chess/pieces/QueenTest.java
  src/test/java/com/woowatechcamp/chess/pieces/RookTest.java
Labels: Step1-7

#146 [huiseung] step-7 예외 처리
  chess/READMe.md
  chess/src/main/java/chess/ChessGame.java
  chess/src/main/java/chess/Main.java
Labels: Step1-7

#147 [miiiinju1] step-7 예외 처리
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Main.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/view/ChessView.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/board/PointCalculatorTest.java
  src/test/java/chess/board/RankTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/BlankTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
  src/test/java/chess/view/ChessViewTest.java
Labels: Step1-7

#148 [lass9436] step-6 기물 이동 구현
  src/test/java/Main.java
  src/test/java/chess/Board.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/Position.java
  src/test/java/chess/Rank.java
  src/test/java/chess/pieces/Bishop.java
  src/test/java/chess/pieces/King.java
  src/test/java/chess/pieces/Knight.java
  src/test/java/chess/pieces/NoPiece.java
  src/test/java/chess/pieces/Pawn.java
  src/test/java/chess/pieces/Piece.java
  src/test/java/chess/pieces/Queen.java
  src/test/java/chess/pieces/Rook.java
Labels: Step1-6

#149 [minseok-oh] step-6 기물 이동 구현
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/ChessView.java
  src/main/java/chess/Main.java
  src/main/java/chess/Position.java
  src/main/java/chess/Rank.java
  src/main/java/chess/constant/Color.java
  src/main/java/chess/constant/Direction.java
  src/main/java/chess/constant/Type.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/PieceFactory.java
  src/main/java/chess/pieces/Position.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
Labels: Step1-6

#150 [kariskan] step-8 GUI나 웹으로 구현
  src/main/java/ChessApplication.java
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Rank.java
  src/main/java/chess/Ranks.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/PieceType.java
  src/main/java/view/ChessGUI.java
Labels: Step1-8

#151 [홍은기] step-5 기물 위치 부여 및 점수 계산
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGameManager.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Order.java
  src/main/java/chess/board/Position.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-5

#152 [june-777] step-5 기물 위치 부여 및 점수계산
  src/main/java/woowa/camp/chess/Board.java
  src/main/java/woowa/camp/chess/BoardConstants.java
  src/main/java/woowa/camp/chess/Position.java
  src/main/java/woowa/camp/chess/Rank.java
  src/main/java/woowa/camp/pieces/Color.java
  src/main/java/woowa/camp/pieces/Piece.java
  src/test/java/woowa/camp/chess/BoardTest.java
  src/test/java/woowa/camp/pieces/PieceTest.java
Labels: Step1-5

#155 [minseok-oh] step-7 예외 처리
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Main.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
Labels: Step1-7

#156 [bellingstar] step-6 기물 이동 구현
  .idea/.gitignore
  .idea/checkstyle-idea.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/java-chess.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/chess-procjet.iml
  .idea/modules/chess-procjet.test.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  chess-procjet/src/main/java/org/example/Game.java
  chess-procjet/src/main/java/org/example/chess/board/Board.java
  chess-procjet/src/main/java/org/example/chess/board/BoardInitializeManager.java
  chess-procjet/src/main/java/org/example/chess/board/BoardMoveManager.java
  chess-procjet/src/main/java/org/example/chess/board/BoardScoreManager.java
  chess-procjet/src/main/java/org/example/chess/board/BoardView.java
  chess-procjet/src/main/java/org/example/chess/board/Position.java
  chess-procjet/src/main/java/org/example/chess/board/sort/AscendingPieceComparator.java
  chess-procjet/src/main/java/org/example/chess/board/sort/DescendingPieceComparator.java
  chess-procjet/src/main/java/org/example/chess/pieces/Bishop.java
  chess-procjet/src/main/java/org/example/chess/pieces/Blank.java
  chess-procjet/src/main/java/org/example/chess/pieces/King.java
  chess-procjet/src/main/java/org/example/chess/pieces/Knight.java
  chess-procjet/src/main/java/org/example/chess/pieces/Pawn.java
  chess-procjet/src/main/java/org/example/chess/pieces/Piece.java
  chess-procjet/src/main/java/org/example/chess/pieces/PieceFactory.java
  chess-procjet/src/main/java/org/example/chess/pieces/Queen.java
  chess-procjet/src/main/java/org/example/chess/pieces/Rook.java
  chess-procjet/src/main/java/org/example/chess/pieces/enums/Direction.java
  chess-procjet/src/main/java/org/example/utils/MathUtils.java
  chess-procjet/src/main/java/org/example/utils/StringUtils.java
  chess-procjet/src/test/java/org/example/chess/board/BoardInitializeManagerTest.java
  chess-procjet/src/test/java/org/example/chess/board/BoardMoveManagerTest.java
  chess-procjet/src/test/java/org/example/chess/board/BoardScoreManagerTest.java
  chess-procjet/src/test/java/org/example/chess/board/BoardTest.java
  chess-procjet/src/test/java/org/example/chess/board/PositionTest.java
  chess-procjet/src/test/java/org/example/chess/board/RankTest.java
  chess-procjet/src/test/java/org/example/chess/pieces/PieceTest.java
Labels: Step1-6

#157 [Hyeon-Uk] step-6 기물 이동 구현 / step-7 예외 처리
  src/main/java/chess/Board.java
  src/main/java/chess/BoardGame.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/ConsoleGameManager.java
  src/main/java/chess/GameManager.java
  src/main/java/chess/Main.java
  src/main/java/chess/PieceCreator.java
  src/main/java/chess/PieceCreatorWithFactory.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/ChessPiece.java
  src/main/java/chess/pieces/Course.java
  src/main/java/chess/pieces/Direction.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/NoPiece.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/PieceFactory.java
  src/main/java/chess/pieces/PieceTypes.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/view/ConsoleGameView.java
  src/main/java/chess/view/ConsoleInputView.java
  src/main/java/chess/view/ConsoleOutputView.java
  src/main/java/chess/view/GameInputView.java
  src/main/java/chess/view/GameOutputView.java
  src/main/java/chess/view/GameView.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/ChessGameTest.java
  src/test/java/chess/pieces/ChessPieceTest.java
  src/test/java/chess/pieces/PieceFactoryTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step1-6, Step1-7

#154 [tidavid1] step-8 GUI나 웹으로 구현
  README.md
  src/main/java/java_chess/ChessApplication.java
  src/main/java/java_chess/application/ChessGUIView.java
  src/main/java/java_chess/application/ChessGame.java
  src/main/java/java_chess/application/properties/GUIProperties.java
  src/main/java/java_chess/chess/Board.java
Labels: Step1-8

#159 [Dr-KoKo] step-5 기물 위치 부여 및 점수계산
  src/main/java/pe/goblin/chess/Main.java
  src/main/java/pe/goblin/chess/board/Board.java
  src/main/java/pe/goblin/chess/board/DefaultScoreEvaluator.java
  src/main/java/pe/goblin/chess/board/ScoreEvaluator.java
  src/main/java/pe/goblin/chess/piece/Piece.java
  src/test/java/pe/goblin/chess/board/BoardTest.java
  src/test/java/pe/goblin/chess/piece/PieceTest.java
Labels: Step1-5

#160 [minnim1010] step-6 기물 이동 구현
  src/main/java/com/wootecam/chess/board/Board.java
  src/main/java/com/wootecam/chess/board/Position.java
  src/main/java/com/wootecam/chess/board/Rank.java
  src/main/java/com/wootecam/chess/board/ScoreCalculationRule.java
  src/main/java/com/wootecam/chess/common/ChessConstraint.java
  src/main/java/com/wootecam/chess/game/ChessGame.java
  src/main/java/com/wootecam/chess/game/ChessGameManager.java
  src/main/java/com/wootecam/chess/move/Direction.java
  src/main/java/com/wootecam/chess/move/PieceMovementManager.java
  src/main/java/com/wootecam/chess/pieces/Bishop.java
  src/main/java/com/wootecam/chess/pieces/King.java
  src/main/java/com/wootecam/chess/pieces/Knight.java
  src/main/java/com/wootecam/chess/pieces/Pawn.java
  src/main/java/com/wootecam/chess/pieces/Piece.java
  src/main/java/com/wootecam/chess/pieces/Queen.java
  src/main/java/com/wootecam/chess/pieces/Rook.java
  src/main/java/com/wootecam/chess/pieces/property/Color.java
  src/main/java/com/wootecam/chess/pieces/property/PieceRepresentation.java
  src/main/java/com/wootecam/chess/pieces/property/PieceType.java
  src/main/java/com/wootecam/chess/utils/AnsiCode.java
  src/main/java/com/wootecam/chess/utils/StringUtils.java
  src/main/java/com/wootecam/chess/view/ChessView.java
  src/test/java/com/wootecam/chess/Converter.java
  src/test/java/com/wootecam/chess/board/BoardInitializerTest.java
  src/test/java/com/wootecam/chess/board/BoardTest.java
  src/test/java/com/wootecam/chess/move/PieceMovementManagerTest.java
  src/test/java/com/wootecam/chess/pieces/BishopTest.java
  src/test/java/com/wootecam/chess/pieces/KingTest.java
  src/test/java/com/wootecam/chess/pieces/KnightTest.java
  src/test/java/com/wootecam/chess/pieces/PawnTest.java
  src/test/java/com/wootecam/chess/pieces/PieceTest.java
  src/test/java/com/wootecam/chess/pieces/QueenTest.java
  src/test/java/com/wootecam/chess/pieces/RookTest.java
Labels: Step1-6

#161 [mirageoasis] step-6 기물 이동 구현
  src/main/java/org/example/Main.java
  src/main/java/org/example/chess/Board.java
  src/main/java/org/example/chess/ChessGame.java
  src/main/java/org/example/chess/Column.java
  src/main/java/org/example/chess/Direction.java
  src/main/java/org/example/chess/Position.java
  src/main/java/org/example/pieces/Bishop.java
  src/main/java/org/example/pieces/King.java
  src/main/java/org/example/pieces/Knight.java
  src/main/java/org/example/pieces/NoPiece.java
  src/main/java/org/example/pieces/Pawn.java
  src/main/java/org/example/pieces/Piece.java
  src/main/java/org/example/pieces/PieceFactory.java
  src/main/java/org/example/pieces/Queen.java
  src/main/java/org/example/pieces/Rook.java
  src/main/java/org/example/utils/BoardPrinter.java
  src/main/java/org/example/utils/BoardScoreCalculator.java
  src/main/java/org/example/utils/Command.java
  src/test/java/org/example/chess/BoardTest.java
  src/test/java/org/example/chess/DirectionTest.java
  src/test/java/org/example/chess/PositionTest.java
  src/test/java/org/example/pieces/PieceTest.java
Labels: Step1-6

#163 [LuizyHub] step-6,7 기물 이동 구현, 예외 처리
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/InputHandler.java
  src/main/java/chess/Main.java
  src/main/java/chess/piece/Bishop.java
  src/main/java/chess/piece/King.java
  src/main/java/chess/piece/Knight.java
  src/main/java/chess/piece/Pawn.java
  src/main/java/chess/piece/Piece.java
  src/main/java/chess/piece/Queen.java
  src/main/java/chess/piece/Rook.java
  src/main/java/chess/util/ChessPoint.java
  src/main/java/chess/util/Direction.java
  src/main/java/chess/util/MoveRule.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PieceTest.java
Labels: Step1-6, Step1-7

#164 [i960107] step-6 기물 이동 구현
  src/main/java/chess/Application.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/BlankPiece.java
  src/main/java/chess/pieces/Direction.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/PieceFactory.java
  src/main/java/chess/pieces/Position.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/sorter/PointSorter.java
  src/main/java/chess/sorter/Sorter.java
  src/main/java/chess/view/ChessView.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/pieces/PieceTestUtil.java
Labels: Step1-6

#165 [bellringstar] step-7 예외 처리
  .idea/modules/chess-procjet.main.iml
  chess-procjet/src/main/java/org/example/chess/board/BoardMoveManager.java
  chess-procjet/src/test/java/org/example/chess/board/BoardMoveManagerTest.java
Labels: Step1-7

#167 [kimhyun5u, seungh1024] step-6 기물 이동 구현
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/CommandChanger.java
  src/main/java/chess/Position.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/NoPiece.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/ChessGameTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/pieces/QueenTest.java
Labels: Step1-6

#162 [Hyeon-Uk] step-8 GUI나 웹으로 구현
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Main.java
  src/main/java/chess/pieces/PieceTypes.java
  src/main/java/chess/view/console/ConsoleGameView.java
  src/main/java/chess/view/console/ConsoleInputView.java
  src/main/java/chess/view/console/ConsoleOutputView.java
  src/main/java/chess/view/swing/PieceTileComponent.java
  src/main/java/chess/view/swing/SwingGameViewAndManager.java
  src/main/java/chess/view/swing/SwingViewComponent.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/ChessGameTest.java
  src/test/java/chess/utils/StringUtilsTest.java
Labels: Step1-8
